language: node_js
node_js:
- '5'
env:
  global:
    - secure: "Y4FGp7atG6b0jW3bd8v4XH/KOZEX5tgX0vy9YUL6iVYlaHYQc3Yje1rxzS9a+0F3iGT/gAsdXd/cfd/HgKgv6OSl8X7TObC33eWsH8lPq0bgqasmPctsO+dZBuC67GYjl4ZjPVjOb0SLuJDKntMgHUfTS/9gx2+G///6atLJu/kMTzq7Qiwilh+O29+mOuBEBaudK+PgqgqT5GgGUHQ5ixPo3ixW8AOumi+E0HlXIddWonRBkDOSKw2xHsDEUJL2N0x17/vS8ysJwW6kMrxTFk7Iykg+4O6ss0n82JdBwkKKKT+UWs/6XQFcSQ7mY2gMYnXgjh6sReYQyo3ri4hkl5vQFmVK/2FlinswBxzn8dmi1y+Gip3icz8Vv1P3gELOl6ywi5ULbHiP254jj4H17rJafyBRwpfIPLdWeIp4KLqh8VIP0LiLLjf4spcMnZaz+lUtiEN5m8/z/B7O8skys/RVNZyBOiZAcPpOXtDCqoJBcjC1ci+qzx9TgSlAdmHNGWZ0hhjznwQSrj6c8UiRcc0u4hwEsdVSlAWEcBbJHLXd9f5USZN8M+5n9yBfSq0y7pKjedkbtkp8MaPapGzI9nHnW/MbskRejlS0wYBezqNnNdfwblGs3a3p3ZyR4HARc59UdVZ0IfEbsZD5jHe5SoPnU+VrFJ9s6QBCMZrvn54="
notifications:
  slack:
    secure: "F//+20hJqhfhMm4rCZQXlLn5ZdyfoYzhzvxeutT13r/ntH1EvnZ6tVsnXgk60yTHN38w4+PGsvRZUpRdvuc87q14kBtFttmEs1qrTCTLuDI8V+72Wg1IvRZgnzOud3ncSp0nE/VOpeosv+YTCpcDAR25Tsw1ig+683x43ASjR0rKso14lfAaTmt8HwpydbuXMR3O+hrKyiORvdHHpIO9db/KTL2WfZxVeMg7DDu/G4tF8foYou3HylLctaQFhKqiYuCQeccPnr+Kv0IUlwqyehCautpCE5yjW7U4b0New55jmtmT/crrczleJ3j74heDB6gSNpB2JxzR2mme/I+eSmKUaCrHM7ezUfqaFUMCR2FjJuAFXY2EfAVmrUyXPwEMhU8+I01HCsuUk+E+mwZcUfUHDM7R7Oe+6F7ajVdl/s86FR91kiJuL2BmZ3SwvSQkor4QKOmJjUkZWDrHqedUr3AxM/uKuCeK7mJ5V79aDIVymrgL3V9fK8nrNe3v2QwNOhbNHec/CIaO90Mer1vSHgMEKWaSyR+zNF5nOBROGQWsOSulGPTimKhk/CkJ1RR9QIheevcYjpZafarV2OK6UFsWU7dvKbx8QFXmXNIM5Fis2z7Vl5VZHUBWxoqGGXl/QsysXCT60wD/rr2MgfxPeFNQO+aEakANMfr2MgzbdpI="
before_install: npm install -g grunt-cli
install: npm install
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
